apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
  - host: soemthing.example.internal   # map this to your LB IP in /etc/hosts for testing
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 3001
      - path: /discounts
        pathType: Prefix
        backend:
          service:
            name: discounts
            port:
              number: 3002
      - path: /items
        pathType: Prefix
        backend:
          service:
            name: items
            port:
              number: 3003
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
