apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
      - name: items
        image: scolas3/items:1.0
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: general-secrets
              key: secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: general-secrets
              key: mongodb_uri
        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: general-secrets
              key: cloud_name
        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: general-secrets
              key: cloud_api_key
        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              name: general-secrets
              key: cloud_api_secret
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
